# Generated by Django 5.1.4 on 2025-02-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filtros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(default=None, null=True)),
                ('periodo', models.CharField(default=None, null=True)),
                ('ingresso', models.CharField(default=None, null=True)),
                ('sexo', models.CharField(default=None, null=True)),
                ('cor', models.CharField(default=None, null=True)),
                ('nacionalidade', models.CharField(default=None, null=True)),
                ('cidade_nascimento', models.CharField(default=None, null=True)),
                ('cidade_moradia', models.CharField(default=None, null=True)),
                ('mensagem', models.TextField(default=None, null=True)),
            ],
        ),
    ]
