# Generated by Django 5.1.4 on 2025-02-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_filtros_cidade_moradia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtros',
            name='campo',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
