# Generated by Django 5.1.4 on 2025-02-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_filtros_campo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtros',
            old_name='campo',
            new_name='variavel_interesse',
        ),
    ]
