# Generated by Django 5.1.4 on 2025-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_rename_campo_filtros_variavel_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtros',
            name='cidade_moradia',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='filtros',
            name='cidade_nascimento',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='filtros',
            name='cor',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='filtros',
            name='curso',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='filtros',
            name='ingresso',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='filtros',
            name='nacionalidade',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='filtros',
            name='periodo',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='filtros',
            name='sexo',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='filtros',
            name='variavel_interesse',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
